CREATE SEQUENCE seq_customer_id
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE seq_address_id
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE seq_department_id
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE seq_branch_id
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE seq_position_id
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE seq_employee_id
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE seq_account_id
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE seq_card_id
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE seq_limit_id
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE seq_transaction_id
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE seq_login_id
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE seq_account_type_id
    START WITH 1
    INCREMENT BY 1;
